export const students = [
  {
    id: 0,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 1,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 2,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 3,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 4,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 5,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 6,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 7,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 8,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 9,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
  {
    id: 10,
    first_name: "Максим",
    last_name: "Мороко",
    phone: "+7 911 876 12 12",
    email: "maksim@gmail.com",
    password: "maksim",
    role: "ученик",
    subject_id: 1,
    abonement_id: 1,
    balance: '100'
  },
]
