export const teachers = [
  {
    id: 0,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 1,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 2,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 3,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 4,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 5,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 6,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 7,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 8,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 9,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 10,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
  {
    id: 11,
    first_name: "Валерия",
    last_name: "Воронин",
    phone: "+7 911 954 89 34",
    email: "valery@gmail.com",
    password: "hello",
    role: "педагог",
    salary_per_hour: "1000",
    subject_id: "piano",
    status: "active"
  },
]
